services:
  redis:
    image: redis:6
    command: redis-server --requirepass Z3fZeK9W6jBfMJY
    container_name: redis
    networks:
      - get5
    restart: always
  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=FJqXv2dd3TeFAn3
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=FJqXv2dd3TeFAn3
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - ./get5db/mysql:/var/lib/mysql
  g5api:
    build: ./G5API
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    volumes:
      - ./public:/Get5API/public
    ports:
      - 3301:3301
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=0fc9c89ce985fa8066398b1be5c730f7 #CHANGME https://www.random.org/cgi-bin/randbyte?nbytes=16&format=h
      - STEAMAPIKEY=FE315E4DAA500737EC827E9A77018971
      - HOSTNAME=https://your-domain.com
      - SHAREDSECRET= Z3TLmUEVpvXdE5H7UdnEbNSySak9gj
      - CLIENTHOME=https://your-domain.com
      - APIURL=https://your-domain.com/api
      - SQLUSER=get5
      - SQLPASSWORD=FJqXv2dd3TeFAn3
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198154367261
      - SUPERADMINS=76561198154367261
      - REDISURL=redis://:Z3fZeK9W6jBfMJY@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: always
  g5v:
    build:
      context: ./G5V
      dockerfile: DockerfileFull
    depends_on:
      - g5api
    container_name: G5V-panel
    networks:
      - get5
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "3080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - g5api
      - g5v
    networks:
      - get5

networks:
  get5:
    driver: bridge